import { saveRemoteProfile, isFirebaseReady } from './firebase-config.js';
const STORAGE_KEY = 'morseKidsAppStateV2';
const DEFAULT_SETTINGS = { vibrationSpeed: 250, soundFrequency: 700, soundEnabled: true, vibrationEnabled: true };
function defaultState() { return { activeProfileId: null, profiles: {} }; }
export function loadAppState() { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); return parsed && typeof parsed === 'object' ? parsed : defaultState(); } catch { return defaultState(); } }
export function saveAppState(state) { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
export function slugifyNickname(nickname) { return nickname.trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-|-$/g, '') || 'morse-kid'; }
export function buildSystemEmail(nickname) { return `${slugifyNickname(nickname)}@morsekids.app`; }
export function buildProfileId(nickname) { return `profile-${slugifyNickname(nickname)}`; }
export function ensureProfileShape(profile = {}) { return { nickname: profile.nickname || '', email: profile.email || buildSystemEmail(profile.nickname || 'kid'), avatarUrl: profile.avatarUrl || '', currentLesson: profile.currentLesson || 1, lastLoginAt: profile.lastLoginAt || new Date().toISOString(), progress: profile.progress || {}, settings: { ...DEFAULT_SETTINGS, ...(profile.settings || {}) } }; }
export function upsertProfile(profileId, profile) { const state = loadAppState(); state.profiles[profileId] = ensureProfileShape({ ...(state.profiles[profileId] || {}), ...profile }); state.activeProfileId = profileId; saveAppState(state); queueRemoteSave(profileId); return state.profiles[profileId]; }
export function getActiveProfile() { const state = loadAppState(); if (!state.activeProfileId) return null; return state.profiles[state.activeProfileId] ? ensureProfileShape(state.profiles[state.activeProfileId]) : null; }
export function getActiveProfileId() { return loadAppState().activeProfileId; }
export function updateActiveProfile(updater) { const state = loadAppState(); if (!state.activeProfileId) return null; const current = ensureProfileShape(state.profiles[state.activeProfileId]); const next = ensureProfileShape(typeof updater === 'function' ? updater(current) : updater); state.profiles[state.activeProfileId] = next; saveAppState(state); queueRemoteSave(state.activeProfileId); return next; }
export function logoutActiveProfile() { const state = loadAppState(); state.activeProfileId = null; saveAppState(state); }
function queueRemoteSave(profileId) { if (!isFirebaseReady()) return; const state = loadAppState(); const profile = state.profiles[profileId]; if (!profile) return; saveRemoteProfile(profileId, profile).catch(() => {}); }
export function getUnlockedLesson(profile, lessonId) { if (lessonId === 1) return true; const previous = profile.progress[String(lessonId - 1)]; return Boolean(previous && previous.stars >= 2); }
export function getCurrentLessonNumber(profile) { for (let lessonId = 1; lessonId <= 23; lessonId += 1) { if (getUnlockedLesson(profile, lessonId) && !(profile.progress[String(lessonId)]?.stars >= 2)) return lessonId; } return 23; }
export function getTotals(profile) { const progressValues = Object.values(profile.progress || {}); const completedLessons = progressValues.filter((item) => item.stars >= 2).length; const totalStars = progressValues.reduce((sum, item) => sum + (item.stars || 0), 0); const totalScore = progressValues.reduce((sum, item) => sum + (item.bestScore || 0), 0); const totalQuestions = progressValues.reduce((sum, item) => sum + (item.totalQuestions || 0), 0); const successRate = totalQuestions ? Math.round((totalScore / totalQuestions) * 100) : 0; return { completedLessons, totalStars, totalScore, successRate }; }
export function saveLessonResult(lessonId, result) { return updateActiveProfile((profile) => { const previous = profile.progress[String(lessonId)] || {}; const progress = { ...profile.progress, [String(lessonId)]: { attempts: (previous.attempts || 0) + 1, stars: Math.max(previous.stars || 0, result.stars), bestScore: Math.max(previous.bestScore || 0, result.score), totalQuestions: result.totalQuestions, lastPlayedAt: new Date().toISOString() } }; return { ...profile, progress, currentLesson: Math.max(profile.currentLesson || 1, result.stars >= 2 ? lessonId + 1 : lessonId), lastLoginAt: new Date().toISOString() }; }); }
export async function playMorseCode(code, settings) { const symbols = code.split(' ').filter(Boolean); const gap = settings.vibrationSpeed; for (const symbol of symbols) { const duration = symbol === '−' ? gap * 3 : gap; if (settings.soundEnabled) playTone(duration, settings.soundFrequency); if (settings.vibrationEnabled && navigator.vibrate) navigator.vibrate(duration); await wait(duration + gap); } }
export function playTone(duration, frequency) { try { const AudioContextRef = window.AudioContext || window.webkitAudioContext; if (!AudioContextRef) return; const audioContext = new AudioContextRef(); const oscillator = audioContext.createOscillator(); const gainNode = audioContext.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = frequency; oscillator.connect(gainNode); gainNode.connect(audioContext.destination); gainNode.gain.setValueAtTime(0.2, audioContext.currentTime); gainNode.gain.exponentialRampToValueAtTime(0.001, audioContext.currentTime + duration / 1000); oscillator.start(); oscillator.stop(audioContext.currentTime + duration / 1000); } catch { return null; } return null; }
export function wait(time) { return new Promise((resolve) => window.setTimeout(resolve, time)); }
